import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Breadcrumbs, SiteFooter, SiteHeader } from '@/components/authority-shell';
import { withPageMetadata } from '@/lib/page-metadata';
import { olqArticles } from '@/lib/olq-articles';
export const dynamicParams = false;
export function generateStaticParams() { return olqArticles.map(([slug]) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const a = olqArticles.find(([s]) => s === slug); if (!a) return {}; return withPageMetadata({ title: `${a[1]} | March Ahead Academy`, description: a[2], alternates: { canonical: `/officer-like-qualities/${slug}/` }, openGraph: { title: a[1], description: a[2], url: `/officer-like-qualities/${slug}/`, type: 'article', images: ['/og-tri-service.webp'] } }); }
export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const a = olqArticles.find(([s]) => s === slug); if (!a) notFound(); return <main className="min-h-screen bg-white text-[#0a1e33]"><SiteHeader /><div className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><Breadcrumbs current={a[1]} tone="light" /><p className="section-kicker">Officer Like Qualities · Academy guidance</p><h1 className="mt-4 max-w-4xl font-heading text-4xl leading-tight sm:text-5xl">{a[1]}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#536371]">{a[2]}</p><article className="mt-10 border-t-2 border-[#4b6228] pt-8"><h2 className="font-heading text-3xl">Turn the idea into development</h2><p className="mt-4 max-w-3xl leading-8 text-[#536371]">{a[3]} OLQs are a public framework for officer development, not a confidential scoring formula. Use them to reflect on behaviour and choices rather than to label yourself or perform a quality on demand.</p><p className="mt-6 max-w-3xl leading-8 text-[#536371]">Continue with the <Link className="text-link" href="/officer-like-qualities/">OLQ hub</Link>, read the <Link className="text-link" href="/selection/ssb/">SSB selection overview</Link>, or <Link className="text-link" href="/ssb-coaching/">discuss individual preparation</Link>.</p></article></div><SiteFooter /></main>; }
