import type { Metadata } from 'next';
import { AuthorityPage } from '@/components/authority-shell';
export const metadata: Metadata = { title: 'SSB Interview Guide | March Ahead Academy', description: 'An ethical, expert-led introduction to SSB and AFSB assessment without tricks or guarantees.' };
export default function Page() { return <AuthorityPage eyebrow="Selection guide" title="SSB: prepare the person, not a performance" lede="A clear, ethical introduction to the assessment journey—built around self-awareness, consistency and genuine development rather than scripts, secrets or ideal answers." status="Foundation guide · Expert commentary awaiting credential verification" sections={[
  { title: 'What the process is trying to understand', body: 'Selection-board assessment considers how a candidate thinks, communicates, works with others, responds to situations and understands their own motivation. No isolated test or polished answer should be treated as a shortcut.' },
  { title: 'Stage I and Stage II', body: 'The process typically begins with screening through OIR and PP&DT, followed for screened-in candidates by psychological tests, group-testing tasks, personal interview and conference. Entry-specific instructions and AFSB differences must be read from current official material.', points: ['Prepare to express your own observations clearly.', 'Reflect honestly on education, family, responsibility, setbacks and choices.', 'Build fitness, awareness and group participation as habits—not last-minute tactics.'] },
  { title: 'What ethical preparation looks like', body: 'Good guidance improves understanding, reflection, communication and familiarity with the process. It does not provide leaked material, claim confidential scoring knowledge or teach candidates to manufacture an officer-like personality.' },
  { title: 'What happens after recommendation', body: 'Recommendation is not final joining. Medical fitness, appeal or review provisions where applicable, merit, vacancies and administrative requirements remain part of the process.' },
]} sources={[{label:'Indian Air Force selection process',href:'https://www.careerairforce.gov.in/selection-process'},{label:'Air Force Selection Board testing',href:'https://careerairforce.gov.in/air-force-selection-board-afsb-testing'},{label:'UPSC active examinations',href:'https://www.upsc.gov.in/examinations/active-exams'}]} related={[{label:'NDA guide',href:'/exams/nda'},{label:'CDS guide',href:'/exams/cds'},{label:'Career Path Finder',href:'/career-paths'}]} />; }
