import type { Metadata } from 'next';
import Link from 'next/link';
import { AlertTriangle, CheckCircle2, ExternalLink, RefreshCw, Scale } from 'lucide-react';
import { SiteHeader } from '@/components/authority-shell';

export const metadata: Metadata = { title: 'Editorial Standards and Corrections | March Ahead Academy', description: 'How March Ahead Academy sources, reviews, labels and corrects Indian defence career guidance.' };

const sourceOrder = ['Current intake notification and its corrigenda', 'Current notice on the relevant official recruitment portal', 'Stable UPSC or service information page', 'Ministry of Defence or PIB material for policy context', 'Secondary context only when no decision-critical fact depends on it'];

export default function Page() {
  return <main className="min-h-screen bg-[#f3f5f2] text-[#0a1e33]"><SiteHeader />
    <section className="command-blue text-white"><div className="mx-auto max-w-6xl px-5 py-16 lg:px-8 lg:py-20"><div className="flex items-center gap-3 text-xs font-bold tracking-[.18em] text-[#9bd1ea] uppercase"><Scale size={16} />Editorial standards</div><h1 className="mt-5 max-w-4xl font-heading text-5xl leading-tight sm:text-6xl">Every important claim should lead back to evidence.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Our rules for sourcing, freshness, uncertainty, independence and corrections are public so readers can judge the quality of our work.</p></div></section>
    <section className="mx-auto max-w-6xl px-5 py-16 lg:px-8 lg:py-20"><div className="grid gap-12 lg:grid-cols-[1fr_320px]"><article className="space-y-12"><section><p className="section-kicker">Source hierarchy</p><h2 className="mt-3 font-heading text-3xl">What controls our answer</h2><ol className="mt-6 grid gap-3">{sourceOrder.map((item,index) => <li key={item} className="flex gap-4 border border-[#cbd3ce] bg-white p-4"><span className="font-heading text-[#397fa8]">0{index + 1}</span><span className="text-sm leading-6">{item}</span></li>)}</ol><p className="mt-4 text-sm leading-6 text-[#5c6974]">Search snippets, coaching websites and AI-generated answers are not evidence.</p></section>
      <section><p className="section-kicker">Review and labelling</p><h2 className="mt-3 font-heading text-3xl">Freshness is part of accuracy</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="bg-white p-5"><RefreshCw className="text-[#397fa8]" /><h3 className="mt-4 font-bold">Live facts</h3><p className="mt-2 text-sm leading-6 text-[#5c6974]">Applications, deadlines, vacancies, corrigenda and results require working-day monitoring during active windows.</p></div><div className="bg-white p-5"><CheckCircle2 className="text-[#4b6228]" /><h3 className="mt-4 font-bold">Evergreen guidance</h3><p className="mt-2 text-sm leading-6 text-[#5c6974]">Entry and selection explanations are reviewed at least every 90 days and after relevant official changes.</p></div></div></section>
      <section><p className="section-kicker">Corrections</p><h2 className="mt-3 font-heading text-3xl">We correct transparently</h2><p className="mt-4 leading-8 text-[#536371]">When a material error is confirmed, we correct the page, update its review date and record what changed. When official sources conflict, we label the issue “verification in progress” rather than presenting a definitive answer.</p><div className="mt-5 flex gap-3 border-l-4 border-[#e88620] bg-white p-5"><AlertTriangle className="shrink-0 text-[#b96516]" /><p className="text-sm leading-6"><strong>Correction channel pending:</strong> a public email address will be added after the academy approves its official contact. Until then, no unverified contact details will be published.</p></div></section>
      <section><p className="section-kicker">Independence</p><h2 className="mt-3 font-heading text-3xl">What we will not claim</h2><ul className="mt-5 grid gap-3 text-sm">{['Guaranteed selection, medical clearance or a “sure-shot” method','Government affiliation, endorsement or privileged selection access','Predicted cut-offs presented as official facts','Success rates, testimonials or credentials without supporting evidence and permission'].map(item => <li key={item} className="flex gap-3 bg-white p-4"><span className="mt-2 h-2 w-2 shrink-0 bg-[#4b6228]" />{item}</li>)}</ul></section></article>
      <aside><div className="sticky top-6 border-t-4 border-[#397fa8] bg-white p-6"><p className="text-xs font-bold tracking-[.16em] text-[#397fa8] uppercase">Inspect the evidence</p><p className="mt-3 text-sm leading-6 text-[#5c6974]">See which official authorities are monitored and what each one controls.</p><Link href="/notifications" className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Open source tracker <ExternalLink size={14} /></Link><hr className="my-6 border-[#dde3df]" /><p className="text-xs leading-5 text-[#697781]">Policy version 1.0<br />Published 6 September 2026<br />Next policy review: 6 December 2026</p></div></aside></div></section>
  </main>;
}
