import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, ShieldCheck, MessageCircle, Lightbulb } from 'lucide-react';
import { withPageMetadata } from '@/lib/page-metadata';
import { Breadcrumbs, SiteFooter, SiteHeader } from '@/components/authority-shell';
const title = 'Officer Like Qualities (OLQs): What Candidates Should Understand';
const description = 'A responsible guide to Officer Like Qualities, leadership, responsibility, communication, cooperation, initiative and decision-making in officer selection.';
export const metadata: Metadata = withPageMetadata({ title: `${title} | March Ahead Academy`, description, alternates: { canonical: '/officer-like-qualities/' }, openGraph: { title, description, url: '/officer-like-qualities/', type: 'website', images: ['/og-tri-service.webp'] } });
const topics = [['Leadership and responsibility', ShieldCheck, 'Explore leadership as accountable action, not performance or a label to claim.'], ['Communication and cooperation', MessageCircle, 'Practise listening, clarity and contribution in real group settings.'], ['Initiative and decisions', Lightbulb, 'Reflect on how you act with incomplete information and learn from outcomes.']] as const;
export default function Page() { return <main className="min-h-screen bg-white text-[#0a1e33]"><SiteHeader /><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><Breadcrumbs current="Officer Like Qualities" tone="light" /><p className="section-kicker">SSB knowledge centre · officer selection</p><h1 className="mt-4 max-w-4xl font-heading text-4xl leading-tight sm:text-5xl">{title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#536371]">OLQs are best understood as a public framework for thinking about officer development—not a confidential formula or a checklist of perfect answers.</p><section className="mt-10 grid gap-6 md:grid-cols-3">{topics.map(([label, Icon, copy]) => <article key={label} className="border-t-2 border-[#397fa8] p-6"><Icon className="text-[#397fa8]" size={28} aria-hidden="true" /><h2 className="mt-4 font-heading text-2xl">{label}</h2><p className="mt-3 leading-7 text-[#536371]">{copy}</p></article>)}</section><section className="mt-12 border-t border-[#d8e1dd] pt-8"><h2 className="font-heading text-3xl">Use OLQs as development prompts</h2><p className="mt-4 max-w-3xl leading-8 text-[#536371]">Read the <Link className="text-link" href="/selection/ssb/">SSB selection overview</Link>, connect the framework to your own experiences and seek feedback on habits you can change. March Ahead Academy does not claim to disclose assessor formulas or predict outcomes.</p></section></div><SiteFooter /></main>; }
