import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { withPageMetadata } from '@/lib/page-metadata';
import { Breadcrumbs, SiteFooter, SiteHeader } from '@/components/authority-shell';
import { ndaArticles } from '@/lib/nda-articles';
export const dynamicParams = false;
export function generateStaticParams() { return ndaArticles.map(([slug]) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const a = ndaArticles.find(([s]) => s === slug); if (!a) return {}; return withPageMetadata({ title: `${a[1]} | March Ahead Academy`, description: a[2], alternates: { canonical: `/exams/nda/${slug}/` }, openGraph: { title: a[1], description: a[2], url: `/exams/nda/${slug}/`, type: 'article', images: ['/og-tri-service.webp'] } }); }
export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const a = ndaArticles.find(([s]) => s === slug); if (!a) notFound(); return <main className="min-h-screen bg-white text-[#0a1e33]"><SiteHeader /><div className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><Breadcrumbs current={a[1]} tone="light" /><p className="section-kicker">NDA & Naval Academy · Academy guidance</p><h1 className="mt-4 max-w-4xl font-heading text-4xl leading-tight sm:text-5xl">{a[1]}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#536371]">{a[2]}</p><article className="mt-10 border-t-2 border-[#4b6228] pt-8"><h2 className="font-heading text-3xl">What to focus on</h2><p className="mt-4 max-w-3xl leading-8 text-[#536371]">{a[3]}</p><h2 className="mt-10 font-heading text-3xl">Use the current notice as the authority</h2><p className="mt-4 max-w-3xl leading-8 text-[#536371]">Dates, vacancies, eligibility windows, syllabus details and selection conditions can change by examination cycle. March Ahead Academy explains the pathway and helps organise preparation; the active UPSC and service notification controls your application.</p><p className="mt-8 leading-8 text-[#536371]"><Link className="text-link" href="/exams/nda/">Return to the NDA hub</Link> · <Link className="text-link" href="/selection/ssb/">Understand SSB</Link> · <Link className="text-link" href="/ssb-coaching/">Explore one-on-one coaching</Link></p></article><nav aria-label="More NDA guides" className="mt-10 border-t border-[#d8e1dd] pt-8"><p className="text-xs font-bold tracking-[.15em] text-[#397fa8] uppercase">More NDA guides</p><div className="mt-4 flex flex-wrap gap-3">{ndaArticles.filter(([s]) => s !== slug).map(([s, label]) => <Link key={s} href={`/exams/nda/${s}/`} className="linked-panel border border-[#d8e1dd] px-4 py-3 font-semibold text-[#2f6f94]">{label} <ArrowRight className="ml-1 inline" size={16} aria-hidden="true" /></Link>)}</div></nav></div><SiteFooter /></main>; }
