import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Users, Route, Mic2 } from 'lucide-react';
import { withPageMetadata } from '@/lib/page-metadata';
import { Breadcrumbs, SiteFooter, SiteHeader } from '@/components/authority-shell';
const title = 'SSB GTO Tasks: GD, GPE, PGT, HGT & More | March Ahead Academy';
const description = 'Understand SSB group testing and GTO preparation: discussion, planning, outdoor tasks, command task, lecturette and individual obstacles.';
export const metadata: Metadata = withPageMetadata({ title, description, alternates: { canonical: '/ssb-gto/' }, openGraph: { title, description, url: '/ssb-gto/', type: 'website', images: ['/og-tri-service.webp'] } });
const topics = [['Group testing overview', '/selection/ssb/group-testing/', Users, 'Understand cooperation, listening and responsible contribution.'], ['Group discussion', '/selection/ssb/group-discussion/', Route, 'Practise exchanging views without treating volume or domination as a shortcut.'], ['Personal interview context', '/selection/ssb/personal-interview/', Mic2, 'Connect group preparation with the wider SSB journey and your own examples.']] as const;
export default function Page() { return <main className="min-h-screen bg-white text-[#0a1e33]"><SiteHeader /><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><Breadcrumbs current="SSB GTO" tone="light" /><p className="section-kicker">SSB knowledge centre · group testing</p><h1 className="mt-4 max-w-4xl font-heading text-4xl leading-tight sm:text-5xl">SSB GTO Tasks and Responsible Preparation</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#536371]">Build an accurate picture of GD, GPE, PGT, HGT, command task, lecturette and individual obstacles—then practise the habits that can meaningfully transfer online.</p><section className="mt-10 grid gap-6 md:grid-cols-3">{topics.map(([label, href, Icon, copy]) => <Link key={href} href={href} className="linked-panel border-t-2 border-[#4b6228] p-6"><Icon className="text-[#4b6228]" size={28} aria-hidden="true" /><h2 className="mt-4 font-heading text-2xl">{label}</h2><p className="mt-3 leading-7 text-[#536371]">{copy}</p><span className="mt-5 inline-flex items-center gap-2 font-bold text-[#2f6f94]">Open guide <ArrowRight size={17} aria-hidden="true" /></span></Link>)}</section><section className="mt-12 border-t border-[#d8e1dd] pt-8"><h2 className="font-heading text-3xl">What online preparation can—and cannot—do</h2><p className="mt-4 max-w-3xl leading-8 text-[#536371]">Online guidance can clarify instructions, help you reflect on communication and cooperation, and suggest safe ways to practise planning. It cannot recreate an assessed group, prescribe a guaranteed behaviour or reveal confidential scoring formulas. Develop teamwork through real activities as well as guided review.</p></section></div><SiteFooter /></main>; }
