import type { ClusterGuide } from '@/lib/next-cluster-guides';
const cdsSources = [
  { label: 'UPSC: CDS II 2026 examination and notification', href: 'https://www.upsc.gov.in/examinations/Combined%20Defence%20Services%20Examination%20%28II%29%2C%202026' },
  { label: 'UPSC: examination notifications', href: 'https://www.upsc.gov.in/exams-related-info/exam-notification' },
  { label: 'UPSC: official previous question papers', href: 'https://www.upsc.gov.in/examinations/previous-question-papers' },
];
const afcatSources = [
  { label: 'Indian Air Force: current notifications', href: 'https://www.careerairforce.gov.in/notification' },
  { label: 'AFCAT 02/2026 official notice (cycle-specific reference)', href: 'https://www.careerairforce.gov.in/sites/default/files/inline-files/AFCAT-Cycle-02-2026-Notification.pdf' },
  { label: 'Official AFCAT syllabus', href: 'https://afcat.edcil.co.in/assets/images/guidelines/download/afcatsektsyllabus.pdf' },
];
export const examDetailGuides: ClusterGuide[] = [
  {
    path: '/exams/cds/eligibility/', parent: '/exams/cds/', parentTitle: 'CDS examination guide',
    title: 'CDS Eligibility: Check Age, Education and Academy Choices',
    description: 'Check CDS eligibility academy by academy, including education, birth-date windows, final-year evidence and the documents needed to resolve uncertainty.',
    sections: [
      { title: 'There is no single CDS eligibility answer', body: 'CDS connects candidates with different academy routes. Start with the examination cycle and academy you are considering, not a generic age chart. Education, date of birth, nationality, marital-status conditions and other personal requirements must be checked together. This guide shows how to organise those checks; it does not declare an individual eligible without their details and the applicable notice.' },
      { title: 'Compare the academy requirements separately', body: 'IMA and OTA, INA and AFA have different educational provisions. The Army graduate routes, Navy engineering route and Air Force qualification provisions should be read separately in the UPSC notice. Do not assume that qualifying for one academy makes all preferences available. Record the exact qualification wording beside the name on your degree and, where required, your school subjects. If equivalence is unclear, seek clarification through the official channel rather than guessing from a similar course name.' },
      { title: 'How to check the CDS age limit', body: 'Find the inclusive birth-date window for your academy and course. Compare both boundaries with the date recorded in the prescribed certificate. A rounded age is not enough, and the same calculation cannot simply be reused for another intake. Check any exception only if the notice expressly provides it and you meet its evidence requirements. Do not calculate eligibility by adding a year to an old internet table.' },
      { title: 'Final-year candidates and evidence deadlines', body: 'Read the provision for candidates still completing a degree, including any conditions about academic status and when proof must be supplied. An application being accepted online is not proof that a degree-completion requirement has been met. Keep examination schedules and university documentation organised, and distinguish application-time declarations from evidence required later. If a deadline is incompatible with your expected result, investigate before relying on the route.' },
      { title: 'Create a one-page eligibility record', body: 'Use a private checklist with one row per requirement. Record the clause, your supporting document and the result of the comparison. Mark an unresolved point clearly and quote the relevant clause when asking the recruitment authority. Do not publish identity documents or full personal details in public discussion groups.', points: ['Examination cycle, academy and course.', 'Documented date of birth and permitted window.', 'Degree, subjects and completion status.', 'Nationality and other personal conditions.', 'Evidence deadlines and any unresolved qualification question.'] },
      { title: 'Eligibility is only the first decision', body: 'Once the route appears to fit, compare the written papers, subsequent SSB or AFSB process and training commitment. Medical fitness and later selection requirements remain separate. Use the preparation-plan guide to organise study, and recheck amendments before applying. Coaching can help you understand the steps and organise questions; it cannot replace the recruitment authority’s eligibility decision.' },
    ], sources: cdsSources,
  },
  {
    path: '/exams/cds/syllabus/', parent: '/exams/cds/', parentTitle: 'CDS examination guide',
    title: 'CDS Syllabus Guide: English, General Knowledge and Mathematics',
    description: 'Understand the CDS paper combination for your academy and turn the official English, GK and Elementary Mathematics syllabus into a study checklist.',
    sections: [
      { title: 'Start with the paper combination', body: 'CDS preparation depends on the academy route. The IMA, INA and AFA written combination includes English, General Knowledge and Elementary Mathematics; OTA uses English and General Knowledge. Verify the applicable scheme in your examination notice before choosing tests or a timetable. This is a study-oriented overview rather than a replacement for the complete UPSC syllabus, marking instructions or examination timetable.' },
      { title: 'English: understand language in context', body: 'Use official papers to see how understanding and use of English are tested. During preparation, separate comprehension, vocabulary and sentence-level errors. For a passage, identify the evidence that supports your answer. For a usage question, explain the sentence rather than remembering only the option letter. Keep a short record of recurring difficulties and revisit them with fresh examples. Avoid treating a commercial topic list as an official promise about question distribution.' },
      { title: 'General Knowledge: organise the breadth', body: 'Build a subject map from the notice, then connect practice questions with the relevant background. History, geography, general science and current events need different kinds of revision. For a changing fact, record the date and source. For a stable concept, explain it in ordinary language and test it later. A large daily headline list is not a substitute for understanding the subject behind a question.' },
      { title: 'Elementary Mathematics: practise methods', body: 'Where Mathematics applies, organise the syllabus into arithmetic, algebra, trigonometry, geometry, mensuration and statistics. Use the detailed official list to fill in the subtopics rather than treating these headings as complete coverage. For each weakness, work through the reasoning, solve a fresh problem unaided and then introduce time limits. A formula sheet helps revision only if you know when and why each relation applies.' },
      { title: 'Turn topics into measurable preparation', body: 'For every topic, record whether you have studied it, attempted questions and reviewed errors. These are different stages: having read a chapter does not mean you can use it under examination conditions. Start with a realistic number of topics and reserve time for reattempts. This Academy checklist supports planning; it is not a predicted weightage or a claim that all topics need equal time.', points: ['Topic and official syllabus reference.', 'Diagnostic question or paper source.', 'Error cause and concept to revisit.', 'Fresh reattempt and next revision date.'] },
      { title: 'Use official papers without overpredicting', body: 'Compare more than one previous paper to understand the range of questions. Follow the marking and time instructions for your intended examination when taking a full practice paper. Review unanswered as well as incorrect questions. Do not infer a future cutoff or topic allocation from a single past paper. The preparation-plan guide explains how to combine subject work, timed practice and correction in a sustainable week.' },
    ], sources: cdsSources,
  },
  {
    path: '/exams/afcat/eligibility/', parent: '/exams/afcat/', parentTitle: 'AFCAT examination guide',
    title: 'AFCAT Eligibility: Branch, Education and Age-Window Checks',
    description: 'Check AFCAT eligibility for your intended branch using the current IAF notification, qualification wording, date-of-birth window and evidence requirements.',
    sections: [
      { title: 'Check a branch and a cycle', body: 'AFCAT is not a single qualification rule shared by every Flying, Ground Duty Technical and Ground Duty Non-Technical opportunity. Identify the notified cycle and the branch you want to investigate. A degree, school subject or percentage condition from a different branch cannot settle your eligibility. The linked cycle notice is a reference, not an announcement that applications remain open.' },
      { title: 'Match the educational wording', body: 'Read the complete branch row and its notes. Record the required degree, any school-subject conditions, marks provisions and accepted disciplines exactly as stated. Compare them with your documents rather than with a shortened description of your course. Technical and specialist branches can have detailed qualification lists. If your degree title is not a clear match, use the official enquiry channel instead of selecting the closest-looking option on a form.' },
      { title: 'Compare the birth-date boundaries', body: 'Use the date-of-birth window and reference date given for your branch and entry. Check both ends against your prescribed evidence. Do not treat a broad phrase such as “graduate age” as a rule, or transfer a relaxation from a different category. Read any exception with its accompanying conditions and proof requirements. Recheck the calculation for a later cycle instead of assuming an earlier eligibility result carries forward.' },
      { title: 'Final-year and other personal conditions', body: 'If you are still studying, check academic-status conditions and the deadline for producing qualification evidence. Review nationality, marital-status and any service-related or previous-selection provisions that apply to you. These checks are distinct from written-exam preparation. Keep an unresolved matter visible until you have a reliable answer; submission of a form or issue of an admit card should not be treated as a final qualification decision.' },
      { title: 'A practical evidence checklist', body: 'Create one row for each intended branch, with the relevant notification paragraph and your supporting document. This makes it easier to spot a missing school subject, an uncertain degree match or a completion deadline. Keep sensitive records private and supply them only through legitimate channels when required.', points: ['Cycle, course and exact branch name.', 'Birth-date window and supporting certificate.', 'School subjects and marks where required.', 'Degree title, marks and completion evidence.', 'Personal eligibility conditions and outstanding questions.'] },
      { title: 'From eligibility to preparation', body: 'After checking the route, move to the written syllabus and AFSB familiarisation. Medical and selection requirements still need separate attention. If you consult the Academy, bring the specific clause you are unsure about and a non-sensitive description of the issue. Coaching can help organise your preparation, but the IAF decides eligibility. Always revisit an amended notice before relying on a previous checklist.' },
    ], sources: afcatSources,
  },
  {
    path: '/exams/afcat/syllabus/', parent: '/exams/afcat/', parentTitle: 'AFCAT examination guide',
    title: 'AFCAT Syllabus Guide: English, Awareness, Numerical Ability and Reasoning',
    description: 'Map the official AFCAT syllabus into practical subject preparation, with concept checks, reliable reading and an error-review routine.',
    sections: [
      { title: 'Use the official syllabus as your map', body: 'AFCAT covers English, General Awareness, Numerical Ability, and Reasoning and Military Aptitude. Use the official syllabus document together with the examination notice for the detailed topic list and applicable scheme. This overview helps organise study; it does not replace the notified requirements or claim a fixed number of questions from each topic. Confirm any additional entry-specific assessment separately rather than relying on an old coaching bundle.' },
      { title: 'English: read for meaning and usage', body: 'Practise understanding passages, selecting words in context and explaining sentence-level choices. Keep examples of mistakes rather than an unmanageable list of isolated vocabulary. When an answer surprises you, identify the clue or grammatical relationship you missed. Reattempt with new material to check whether you learned the principle rather than the answer. Use the detailed official syllabus to ensure your practice is not confined to your favourite question type.' },
      { title: 'General Awareness: build connections', body: 'Organise notes into subjects such as history, geography, science, public affairs and defence awareness, checking the full official list for scope. Connect a current event with the institution, place or concept involved. Record dates for facts that change and verify important claims with reliable sources. Distinguish understanding a topic from recognising a headline. A short, revisited set of notes can be more useful than an expanding archive you never test.' },
      { title: 'Numerical Ability: understand the calculation', body: 'Build a topic checklist from the official document. For each type of problem, practise translating the wording into quantities and relationships before working on speed. Write units where they help prevent errors. Compare different methods only after you can explain one reliable method. During review, distinguish a missing concept from a calculation slip or a misread condition; each needs a different correction.' },
      { title: 'Reasoning and Military Aptitude', body: 'Practise recognising relationships in verbal and non-verbal material. Describe the rule you think applies and test it against all the information, rather than choosing the first pattern that looks plausible. Vary the examples so familiarity with a diagram does not masquerade as understanding. Avoid claims that a single shortcut solves an entire category. An error log should capture why an alternative failed, not only which option was correct.' },
      { title: 'Move from coverage to timed application', body: 'Track studied topics, successful fresh attempts and recurring errors separately. Introduce timed sets, then broader practice using the scheme relevant to your examination. Review every set before collecting more scores. Check disputed answers and do not use an unofficial mock to predict a cutoff or branch outcome. The AFCAT preparation-plan guide helps combine these subjects with a realistic weekly routine and later AFSB preparation.' },
    ], sources: afcatSources,
  },
];
