import { outdoorGtoGuides } from '@/lib/outdoor-gto-guides';
import { examDetailGuides } from '@/lib/exam-detail-guides';
export type ClusterGuide = {
  path: string; title: string; description: string; parent: string; parentTitle: string;
  sections: { title: string; body: string; points?: string[] }[];
  sources: { label: string; href: string }[];
};
const afsb = { label: 'Indian Air Force: AFSB testing', href: 'https://careerairforce.gov.in/air-force-selection-board-afsb-testing' };
export const nextClusterGuides: ClusterGuide[] = [
  ...outdoorGtoGuides,
  ...examDetailGuides,
  {
    path: '/ssb-gto/group-planning-exercise/', parent: '/ssb-gto/', parentTitle: 'SSB GTO preparation',
    title: 'SSB Group Planning Exercise: Reasoning, Priorities and Teamwork',
    description: 'Prepare for GPE through careful reading, realistic use of time and resources, and collaborative planning. Try an original practice exercise.',
    sections: [
      { title: 'What to practise for a planning exercise', body: 'Group planning involves making sense of a situation and working towards a practical proposal. The wider group-testing process includes mental and physical activities; a planning exercise is not simply a speech contest. Start by identifying the objective, the known facts and the constraints. Keep assumptions separate. This guide offers Academy practice methods, not an official scenario, task sequence or scoring system.' },
      { title: 'Check whether the plan can actually work', body: 'Before defending a solution, test its dependencies. Does a person need to be in two places at once? Have you allowed time for the activity itself as well as travel? Does the proposed resource exist in the information supplied? A plan can sound decisive while relying on an unavailable vehicle or an impossible connection. Where a detail is unknown, explain the uncertainty rather than silently treating it as favourable.', points: ['List objectives and deadlines before assigning roles.', 'Record resources and their availability.', 'Check travel, action and handover time separately.', 'Identify what happens if a key assumption fails.'] },
      { title: 'An original, low-risk practice scenario', body: 'Your college team must set up two registration desks by 10:00 and deliver printed programmes to the hall by 09:45. It is 09:00. Four volunteers are available. Each desk requires two people working for 25 minutes. Collecting and delivering the programmes takes one person 20 minutes. Everyone starts together, and all walking time is included in these task durations. Make a feasible schedule, state who does each task and check the deadlines. This fictional logistics exercise develops planning habits; it is not a replica of an SSB problem.' },
      { title: 'Compare alternatives before selecting one', body: 'Write your own plan, then compare it with two peers. One feasible arrangement uses two volunteers for the first desk from 09:00 to 09:25, one for programme delivery until 09:20, and the remaining volunteer joins the returning person to complete the second desk by 09:45. Other workable allocations may exist. Now delay programme delivery by 15 minutes and reconsider the arrangement. Discuss which deadlines still hold and why. The useful outcome is reasoning that others can check, not memorising this example.' },
      { title: 'Work towards a shared plan', body: 'When comparing proposals, name the constraint that makes an alternative stronger or weaker. Build on a useful suggestion even if it was not yours. Clarify responsibilities and the sequence before summarising. An online group can practise this exchange; a one-to-one session can examine your reasoning but cannot reproduce interaction among several candidates. Ask observers to note missed facts, unsupported assumptions and how the group handled disagreement rather than assign an unofficial GTO score.' },
      { title: 'Review one improvement at a time', body: 'After practice, separate reading errors from calculation errors and discussion difficulties. If you missed a deadline, repeat with a fresh scenario and a clearer timeline. If the plan was sound but poorly explained, practise a brief summary of objective, allocation and fallback. Do not turn emergency-themed exercises into invented medical or rescue instructions: use qualified authorities for real emergencies and keep self-created practice safe and hypothetical.' },
    ], sources: [afsb],
  },
  {
    path: '/ssb-gto/lecturette/', parent: '/ssb-gto/', parentTitle: 'SSB GTO preparation',
    title: 'SSB Lecturette Preparation: Clear Ideas Without Memorised Speeches',
    description: 'Practise a short, structured talk with reliable facts, relevant examples and a clear conclusion. Includes a repeatable lecturette practice routine.',
    sections: [
      { title: 'Prepare to organise ideas', body: 'A lecturette is a short individual talk within group testing. Broad familiarity helps, but the timing, topic choices and conduct at your board come from the instructions given there. Your practice should develop the ability to organise an idea quickly, explain it clearly and finish within a chosen limit. A memorised speech may not answer the topic actually presented.' },
      { title: 'Build a small, useful outline', body: 'Start with what the topic means and the point you want to explain. Choose two supporting ideas and a relevant example, then close with a balanced conclusion. For a topic such as public transport, you might discuss access to education and reliability, using an example you understand. Do not force every subject into the same dramatic opening. The outline is a rehearsal aid, not an official assessment template.' },
      { title: 'Research fewer subjects with better understanding', body: 'Choose a mix of familiar social issues, science, education, environment and public affairs. For each, record a short explanation, a reliable source and one uncertainty or competing consideration. Avoid repeating statistics whose date or meaning you cannot explain. If a fact is not essential, a clear qualitative explanation is better than an invented number. Update notes when events change; a confident statement based on an old headline can mislead.' },
      { title: 'A practical speaking exercise', body: 'Write five ordinary topics on separate slips: teamwork in college, responsible technology use, sport, public transport and learning a practical skill. Pick one at random, prepare a brief outline and speak for a practice limit chosen beforehand. Two or three minutes can be a useful self-set exercise, not a claim about the board’s instructions. Record only with consent and keep recordings private.', points: ['Can a listener identify my main point?', 'Does each example support the topic?', 'Did I leave time for a conclusion?', 'Which statement needs better evidence?'] },
      { title: 'Use feedback to change one habit', body: 'Ask a listener to summarise your argument rather than rate your personality. If they remember only the example, make the main point clearer. If you run over time, remove a secondary point rather than accelerate every sentence. Practise a fresh topic after feedback so you develop a transferable habit. Natural pauses and straightforward language can make an explanation easier to follow; exaggerated gestures and accent imitation are not useful targets.' },
      { title: 'Online practice and its limits', body: 'Online sessions can support timed talks, questions and feedback on structure. Check microphone quality and avoid reading from a hidden script. Practising in front of a small in-person group adds a different experience of audience attention. Neither setting provides an official score or predicts recommendation. Connect speaking practice with everyday discussion and reading, and use the interview communication guide when you need help responding to follow-up questions.' },
    ], sources: [afsb, { label: 'Sainik School Kazhakootam: public SSB task overview', href: 'https://www.sainikschooltvm.edu.in/uploads/ckupload/School%20Diary%202025_26_1751955274.pdf' }],
  },
  {
    path: '/exams/cds/preparation-plan/', parent: '/exams/cds/', parentTitle: 'CDS examination guide',
    title: 'CDS Preparation Plan: English, General Knowledge and Mathematics',
    description: 'Build a CDS study plan around your academy preference, official papers, subject diagnostics and a practical weekly review.',
    sections: [
      { title: 'Choose the route before the timetable', body: 'Start with the academy choices and paper combination that apply to your intended entry. CDS preparation for OTA is not identical to preparation for routes requiring Elementary Mathematics. Check the current UPSC notice before allocating time; eligibility, academy availability and the written-paper requirements are separate questions. Keep a private route checklist next to your study plan so preparation does not drift away from the application you intend to make.' },
      { title: 'Use official papers to find your starting level', body: 'Download the relevant English, General Knowledge and, where applicable, Elementary Mathematics papers from UPSC. Attempt manageable sections first and record accuracy and time. Label errors by cause: missing knowledge, misunderstood wording, weak method or rushed execution. A total mark alone cannot tell you what to change. Save the paper year and any answer-key source so you can revisit disputed questions without treating every online solution as authoritative.' },
      { title: 'Study each paper differently', body: 'For English, revisit the sentence or passage and explain why an alternative is unsuitable. For General Knowledge, place a missed fact within a topic and return to it after an interval. For Mathematics, reproduce the method without looking at the worked answer, then compare approaches. Reading more pages will not necessarily repair a calculation habit; solving more questions will not necessarily correct a misunderstanding of a passage.', points: ['English: comprehension, usage and vocabulary in context.', 'General Knowledge: organised subject revision plus current affairs.', 'Mathematics where required: concepts, worked reasoning and timed accuracy.'] },
      { title: 'Build a week around outputs', body: 'Plan a realistic number of study blocks around university or work. Allocate at least one block to correcting previous work rather than new material. A useful weekly output might be a reviewed English set, two revised knowledge topics and a repaired Mathematics weakness. This is an Academy planning example, not a fixed course duration. Protect normal responsibilities and enough recovery time rather than copying an unsustainable timetable from another candidate.' },
      { title: 'Introduce timed papers deliberately', body: 'Move from small timed sets to fuller papers once you can identify the methods involved. Follow the scheme and marking instructions for your examination. After a mock, review unanswered questions as well as wrong ones: did you deliberately defer them, fail to recognise an approach or run out of time? Compare performance across several comparable attempts before changing the plan. Do not treat one unusually strong practice score as a predicted result.' },
      { title: 'Keep the written exam connected to SSB', body: 'Continue reflecting on real academic, work and group experiences while studying. Be able to explain a project, a responsibility and why a service route interests you. Written qualification does not replace subsequent selection stages. When seeking individual help, bring a recent attempted paper and an error log so the conversation can focus on specific difficulties. Revisit your plan weekly and retain changes that improve understanding or accuracy, not merely hours recorded.' },
    ], sources: [{ label: 'UPSC: previous question papers', href: 'https://www.upsc.gov.in/examinations/previous-question-papers' }, { label: 'UPSC: examination notifications', href: 'https://www.upsc.gov.in/exams-related-info/exam-notification' }],
  },
  {
    path: '/exams/afcat/preparation-plan/', parent: '/exams/afcat/', parentTitle: 'AFCAT examination guide',
    title: 'AFCAT Preparation Plan: From Subject Practice to AFSB',
    description: 'Organise AFCAT preparation across English, general awareness, numerical ability and reasoning, with error review and an AFSB transition checklist.',
    sections: [
      { title: 'Separate branch eligibility from preparation', body: 'Before choosing study material, identify the branch and entry conditions you intend to apply under. A preparation plan cannot establish eligibility. Check the current IAF notification for qualifications, dates and selection requirements, and use the official syllabus as the subject checklist. Record unresolved branch questions separately so they are not confused with difficulties in practice questions.' },
      { title: 'Make a subject-by-subject baseline', body: 'The official AFCAT syllabus covers English, General Awareness, Numerical Ability, and Reasoning and Military Aptitude. Begin with a small practice set in each area and note the kinds of errors you make. For English, distinguish vocabulary gaps from misunderstood passages. For numerical questions, distinguish a missing concept from arithmetic slips. For reasoning, write the relationship you identified rather than simply remembering the correct option.' },
      { title: 'A weekly cycle that includes correction', body: 'Rotate shorter subject sessions through the week, leaving a separate block for review and reattempts. Pair reading with English comprehension practice, and organise general-awareness notes by subject rather than accumulating disconnected headlines. For numerical ability, work through the reasoning before adding time pressure. Adapt the number of blocks to your commitments; this routine is an Academy study suggestion, not an official recommended schedule.' },
      { title: 'Use practice tests as feedback', body: 'Check the current examination scheme before choosing timed practice. After each set, record the cause of lost marks and whether you can solve the question unaided later. Separate remembered questions from fresh ones when comparing performance. For disputed answers, verify the underlying fact or method with a reliable source. A mock score is useful for planning but is not a forecast of a cutoff, selection result or branch allocation.', points: ['What did I misunderstand?', 'Can I explain the correct method?', 'Which errors recur across different questions?', 'What will I change in the next practice block?'] },
      { title: 'Prepare for the transition to AFSB', body: 'Read the official AFSB overview and keep documents organised according to the instructions that apply to you. Familiarisation with screening, psychological tests, group activities and interview involves different work from answering written questions. Continue real responsibilities, discussion and reflection rather than postponing all personal preparation until a written result. The later process has its own requirements; written performance does not itself guarantee recommendation or admission.' },
      { title: 'When individual help is useful', body: 'Bring your branch questions, a subject baseline and one reviewed practice set to a consultation. A useful discussion can distinguish a knowledge gap from a planning or communication difficulty. Agree the scope of written-exam support separately from psychology or interview coaching. If you are repeating an attempt, start with observable preparation evidence rather than guessing the cause of an earlier result. Review progress across several weeks and adjust the plan when the evidence warrants it.' },
    ], sources: [{ label: 'IAF official AFCAT syllabus', href: 'https://afcat.edcil.co.in/assets/images/guidelines/download/afcatsektsyllabus.pdf' }, { label: 'Indian Air Force: notifications', href: 'https://www.careerairforce.gov.in/notification' }, afsb],
  },
];
