export const olqArticles = [
  ['leadership', 'Leadership in SSB: What Candidates Should Understand', 'Leadership is accountable action that helps a group move forward, not a performance of authority.', 'Reflect on times you organised work, listened to people and accepted responsibility for an outcome.'],
  ['responsibility', 'Responsibility in Officer Like Qualities', 'Responsibility begins with owning commitments, communicating early and learning from consequences.', 'Use real examples from study, work, family or teams. Separate what you did from what others contributed.'],
  ['communication', 'Communication in SSB: Clarity and Listening', 'Effective communication includes understanding, concise expression and adapting to the person and situation.', 'Practise summarising another person’s view before explaining your own. Clarity is more valuable than volume.'],
  ['cooperation', 'Cooperation and Teamwork in SSB', 'Cooperation means contributing to a shared outcome while respecting information, roles and other people’s ideas.', 'Notice whether your group behaviour makes participation easier. Review how you handle disagreement without withdrawing or dominating.'],
  ['initiative', 'Initiative in Officer Like Qualities', 'Initiative is thoughtful action when a useful next step is available—not impulsive activity for its own sake.', 'Identify a situation where you noticed a need, considered constraints and acted appropriately. Explain what you learned.'],
  ['decision-making', 'Decision-Making in SSB: A Responsible Approach', 'Sound decisions use available information, priorities and consequences, then remain open to correction.', 'Practise explaining what information influenced a choice and what you would do if circumstances changed.'],
] as const;

type Section = { title: string; body: string; points?: string[] };
export const olqSections: Record<string, Section[]> = {
  leadership: [
    { title: 'Leadership begins with the work', body: 'Leadership in everyday preparation means helping people understand a purpose and make progress together. A title, loud voice or early suggestion does not by itself show whether a contribution was useful. Consider how you clarified a problem, included information from others and followed through when the work became difficult.' },
    { title: 'An example worth reflecting on', body: 'Imagine a college project falling behind because two members understand the brief differently. Check the requirement, agree priorities and divide work according to availability. Taking over every task can hide the misunderstanding rather than solve it. Explain your reasoning, invite corrections and check progress before the deadline.' },
    { title: 'Practise in an ordinary setting', body: 'Choose a real shared activity: a study group, sports practice or volunteering commitment. Agree what completion means, ask each person what they can contribute and review the outcome together. Rotate the organising role so you also practise supporting somebody else’s direction.', points: ['What changed because of your contribution?', 'Whose idea improved the plan?', 'What did you do when the first approach failed?', 'What responsibility did you retain after delegating?'] },
    { title: 'Discuss leadership through real examples', body: 'In an interview, describe your own contribution without claiming the group’s entire result. Include limits and mistakes when relevant. In group activities, attend to the actual task and other candidates rather than performing a predefined leadership style. Reflection should help you act more usefully next time.' },
  ],
  responsibility: [
    { title: 'Responsibility is visible in follow-through', body: 'Responsibility includes accepting a reasonable commitment, understanding its consequences and keeping others informed. It also includes recognising when you need help. Saying yes to everything can leave people depending on work you cannot complete.' },
    { title: 'When a commitment goes wrong', body: 'Suppose you promised to organise transport for a college visit and the arrangement falls through. Review when you noticed the problem, whom you informed and which alternatives you checked. A useful account includes what was within your control and what you changed afterwards. Blaming circumstances alone leaves the learning unexplained.' },
    { title: 'A week of practical preparation', body: 'Select one commitment with a real deadline and another person depending on it. Write down the expected result, next action and a check-in point. Complete the work or communicate an obstacle early enough for a useful adjustment. Compare what you promised with what happened.', points: ['Was the commitment realistic?', 'Did someone need to repeatedly remind you?', 'Did you report an error before it became somebody else’s problem?', 'What will make the next commitment more reliable?'] },
    { title: 'Use real responsibilities in your interview', body: 'Family duties, study, employment and community activities can all provide examples. Their value lies in choices you can explain, not how impressive the label sounds. Avoid inventing responsibilities or presenting yourself as solely responsible for a shared achievement.' },
  ],
  communication: [
    { title: 'Clarity includes listening', body: 'Communication is a useful preparation theme across discussion, interview and group work. Begin by understanding the question or instruction. Then explain a relevant idea in language the listener can follow. A prepared speech can be fluent and still fail to answer what was asked.' },
    { title: 'Build a point from evidence', body: 'Choose a familiar topic and explain your view, one reason and one example. Ask a listener to summarise what they understood. If the summary differs from your intention, clarify the missing link rather than merely speaking louder. Separate facts you can support from your interpretation.' },
    { title: 'A discussion exercise', body: 'With a partner, discuss a practical choice such as how to use a college activity budget. Before replying, summarise the other person’s concern. Add your reasoning and identify where you agree. There is no prescribed sentence to reproduce at SSB.', points: ['Did I answer the actual point?', 'Could I shorten my explanation without losing meaning?', 'Did I interrupt before understanding?', 'Did I acknowledge a useful correction?'] },
    { title: 'What online practice can improve', body: 'A live conversation or recording can help you notice pace, relevance and unexplained assumptions. It cannot reproduce every group dynamic. Continue conversations and shared activities offline too. Aim for understandable, thoughtful expression rather than an artificial accent or memorised vocabulary.' },
  ],
  cooperation: [
    { title: 'Cooperation is active participation', body: 'Cooperation involves working towards a shared result while contributing your observations. It does not require agreement with every suggestion. A group benefits when members explain a concern, consider alternatives and support a workable decision once it is understood.' },
    { title: 'Disagreement can improve the plan', body: 'Imagine a team choosing a route for an event while one member notices a timing problem. Ask for the calculation, compare options and adjust the plan if the evidence warrants it. Be ready to revise your preferred idea when another member identifies a better one.' },
    { title: 'Practise shared problem-solving', body: 'Plan a real activity with a few peers. Make responsibilities explicit and agree how to handle a change. Afterwards, ask what helped the team and what slowed it down. Rotate roles and listen to feedback from quieter participants.', points: ['Did I contribute information the group needed?', 'Did I make room for others?', 'Could I disagree without dismissing a person?', 'Did I support the final agreed action?'] },
    { title: 'Prepare with people as well as alone', body: 'Reading about teamwork provides orientation, but cooperation develops through interaction. An online group discussion can provide practice in listening and combining ideas. Outdoor tasks additionally involve physical coordination, equipment and instructions that a video call cannot replicate.' },
  ],
  initiative: [
    { title: 'Notice a need before choosing an action', body: 'Initiative is a helpful way to reflect on whether you identify useful opportunities and act on them. The first action is not automatically the best one. Understand the objective, your role and available resources before deciding what you can reasonably do.' },
    { title: 'Useful action within your role', body: 'If a study group repeatedly loses time locating materials, propose a shared index, ask what format people need and maintain it for a week. The contribution addresses a real problem and is followed through. Announcing several ideas without completing any offers less practical benefit.' },
    { title: 'A small development exercise', body: 'Choose one recurring inconvenience in study, work or a shared activity. Identify a manageable improvement, discuss it with those affected and carry it out. Review whether it helped before expanding it.', points: ['What need did I observe?', 'Did I check relevant permission or constraints?', 'How did I involve the people affected?', 'Did the action solve the problem or create another?'] },
    { title: 'Focus on useful contribution', body: 'In preparation groups, attend to the task rather than competing to speak or move first. Sometimes a useful initiative is to clarify an instruction, check a calculation or help implement somebody else’s idea. Use the same judgement in everyday commitments so examples come from actual experience.' },
  ],
  'decision-making': [
    { title: 'Explain the reasoning behind a choice', body: 'Identify the objective, check relevant information, consider consequences and choose a workable next step. Being decisive does not mean being certain about everything. A reasoned decision can include a condition that would make you reconsider it.' },
    { title: 'Separate facts from assumptions', body: 'In a planning exercise, list what the problem states and what you are assuming. Check time, distance and resource constraints where provided. Do not silently invent transport, equipment or help. Explain an assumption if your plan depends on it and consider an alternative if it is unavailable.' },
    { title: 'Review a decision from real life', body: 'Choose a recent decision about a deadline, project or shared activity. Record the options, information used and outcome. Ask what you knew at the time rather than judging yourself only with hindsight.', points: ['What was the main objective?', 'Which constraint ruled out an option?', 'Who else was affected?', 'What information would have changed the decision?'] },
    { title: 'Practise adapting a plan', body: 'Ask a peer to change one condition in a simple planning problem. Rework your answer and explain the trade-off. This is an Academy learning exercise, not an official test or scoring model. The aim is clearer reasoning and a willingness to correct an unsuitable plan.' },
  ],
};
