import type { ClusterGuide } from '@/lib/next-cluster-guides';
const sources = [
  { label: 'Indian Air Force: interactive indoor and outdoor group tests', href: 'https://careerairforce.gov.in/air-force-selection-board-afsb-testing' },
  { label: 'Sainik School Kazhakootam: public overview of SSB tasks', href: 'https://www.sainikschooltvm.edu.in/uploads/ckupload/School%20Diary%202025_26_1751955110.pdf' },
];
const parent = '/ssb-gto/';
const parentTitle = 'SSB GTO preparation';
export const outdoorGtoGuides: ClusterGuide[] = [
  {
    path: '/ssb-gto/progressive-group-task/', parent, parentTitle,
    title: 'SSB Progressive Group Task: Practical Cooperation and Preparation',
    description: 'Understand PGT at a broad level and practise explaining ideas, following instructions and contributing to a group without memorising obstacle solutions.',
    sections: [
      { title: 'What is the Progressive Group Task?', body: 'PGT is an outdoor group activity within SSB group testing. Candidates work with the task, material and restrictions explained by the Group Testing Officer. Public task lists identify PGT, but a diagram found online cannot tell you the exact problem you will receive. Listen to the briefing and understand the objective before applying an idea from previous practice. This guide focuses on useful preparation habits, not a catalogue of official obstacle solutions.' },
      { title: 'Begin with a shared understanding', body: 'A group can lose time because its members are solving different versions of the problem. In practice, first check what must be moved or achieved, what material is available and which restrictions apply. Explain an idea in a few clear steps and invite a practical question. Do not assume that the person holding equipment has understood the same plan. If instructions are uncertain, clarify them through the appropriate channel instead of inventing a convenient exception.' },
      { title: 'Contribute beyond proposing an idea', body: 'Participation includes noticing a constraint, helping communicate a workable plan and carrying out an agreed role. Repeating a suggestion more loudly does not repair a flaw. When another candidate offers a better approach, help the group understand and implement it. If your proposal fails, identify the specific reason and adapt. None of these actions is an isolated formula for demonstrating an OLQ; they are useful habits in shared work.' },
      { title: 'A safe tabletop preparation exercise', body: 'Use cards to represent people, resources and destinations for an ordinary classroom task. Ask the group to move the cards through a sequence with simple written constraints, such as a resource being available to only one person at a time. One observer checks whether the group explains changes and follows its own rules. This is an Academy communication exercise, not a simulated PGT or a test of physical technique. Do not build raised obstacles or improvised load-bearing structures.' },
      { title: 'Review group behaviour with evidence', body: 'After the exercise, ask each person to identify one action that helped and one moment of confusion. Describe observable behaviour: a missed instruction, an unexplained change or a useful clarification. Avoid labelling somebody a leader or follower from one activity. Repeat with different roles so the same person does not always do the explaining. An individual coaching session can help review these observations, but practising real group interaction requires other participants.' },
      { title: 'What needs an appropriate physical setting', body: 'Outdoor practice requires suitable facilities, equipment and supervision. Online explanations can support understanding and communication, but cannot reproduce handling physical material or coordinating safely on a task. Ask any provider what practical facilities it actually offers. At the selection centre, follow the briefing and safety instructions rather than relying on a memorised technique. Preparation should make you more attentive and adaptable, not more committed to a preselected solution.' },
    ], sources,
  },
  {
    path: '/ssb-gto/half-group-task/', parent, parentTitle,
    title: 'SSB Half Group Task: Contributing in a Smaller Team',
    description: 'Understand HGT in relation to PGT and develop clear communication, shared responsibility and practical cooperation in a smaller group.',
    sections: [
      { title: 'What changes in a smaller group?', body: 'The Half Group Task is an outdoor group-testing activity involving a smaller group than PGT. Follow the instructions provided for your actual task; do not infer fixed group numbers, equipment or timing from a recollection online. A smaller team gives each participant different practical demands, but it does not change cooperation into a contest to monopolise decisions. Prepare to understand the problem and work with whoever is in your group.' },
      { title: 'Make your contribution understandable', body: 'Explain the useful part of an idea before describing every possible variation. Check whether another person sees a constraint you have missed. If you are carrying out an agreed role, communicate what you need and when you are ready. Do not confuse silence with agreement or assume that a teammate asking a question is opposing you. A brief clarification can prevent a longer interruption later.' },
      { title: 'Share responsibility without disappearing', body: 'Small teams need both participation and coordination. Waiting for someone else to decide everything can leave useful information unspoken; directing every action can prevent others from contributing. In ordinary group work, practise identifying a specific responsibility and following through. If a plan changes, confirm the new allocation. The aim is to make the task progress, not to claim a particular role for its own sake.' },
      { title: 'A small-team practice example', body: 'Ask three or four peers to organise a short classroom presentation with limited preparation time. Give each person different source information and require the group to produce one coherent explanation. Afterwards, discuss whether information was shared, whether responsibilities were clear and whether the final explanation contained contradictions. This original exercise develops small-team habits; it does not reproduce an official HGT or its physical demands.' },
      { title: 'Respond to an unworkable suggestion', body: 'Describe the problem with the suggestion rather than attacking the person. For example, explain that an allocation needs the same resource in two places, then propose a feasible adjustment. Be equally willing to reconsider your own idea. Practise changing a plan after new information rather than defending it because you introduced it. Ask an observer to note how the group resolved the issue, not to produce an unofficial SSB rating.' },
      { title: 'Keep online and outdoor preparation distinct', body: 'Online small-group exercises can help with listening and explanation. Physical coordination needs an appropriate setting and competent supervision. Do not improvise apparatus at home or treat a video demonstration as an instruction for construction. Use the PGT guide for broader group habits and the cooperation guide for reflection on everyday teamwork. At the board, the actual briefing determines the task and its boundaries.' },
    ], sources,
  },
  {
    path: '/ssb-gto/command-task/', parent, parentTitle,
    title: 'SSB Command Task: Responsibility, Instructions and Adaptation',
    description: 'Prepare to understand an objective, communicate a practical plan and adapt responsibly without learning scripted command-task solutions.',
    sections: [
      { title: 'Understand the responsibility', body: 'The command task places a candidate in a directing role within an outdoor group-testing activity. The precise task, assistance and restrictions are explained at the board. Familiarity with the name is useful; assuming a known obstacle will appear is not. Preparation can focus on understanding a problem and communicating what needs to happen without pretending to reveal the assessor’s private method.' },
      { title: 'Clarify before directing', body: 'Identify the objective, material and restrictions before giving instructions. A quick instruction is not necessarily a clear one. State what you want done and check that the person helping understands. If there is an uncertainty in the task briefing, resolve it appropriately rather than building a plan on a guess. Distinguish the outcome you are trying to achieve from the first method that occurred to you.' },
      { title: 'Adapt a plan without losing the objective', body: 'When an approach does not work, examine the constraint it failed to satisfy. Change the relevant step rather than issuing several unrelated instructions. Listen to useful information while retaining responsibility for your decisions within the task rules. The purpose of practice is to become clearer and more flexible, not to manufacture a forceful speaking style or claim that a particular gesture earns marks.' },
      { title: 'An everyday responsibility exercise', body: 'Take responsibility for organising a modest shared activity, such as preparing a study-room session with agreed materials and a fixed start time. Explain roles, check readiness and handle a realistic change, such as a missing resource. Afterwards, ask the participants which instruction helped and which was unclear. Rotate responsibility in the next activity. This is an original development exercise, not an SSB simulation.' },
      { title: 'Review decisions, not appearances', body: 'Write down the objective, the information you used, the decision you made and the result. Consider whether an instruction needed more context, whether you noticed a changed condition and whether you acknowledged a mistake. Avoid judging the activity only by how authoritative you sounded. A specific change, such as checking availability before allocating a resource, gives you something useful to practise next.' },
      { title: 'Physical task boundaries', body: 'Outdoor practice belongs in a suitable supervised facility. Do not recreate obstacle structures, load-bearing arrangements or risky techniques from an internet explanation. Online coaching can support discussion of decisions and communication but cannot reproduce the physical task. During selection, follow the given rules and safety instructions. Neither a successful practice activity nor a familiar obstacle predicts recommendation.' },
    ], sources,
  },
  {
    path: '/ssb-gto/individual-obstacles/', parent, parentTitle,
    title: 'SSB Individual Obstacles: Familiarisation and Safe Preparation',
    description: 'Understand the place of individual obstacles in group testing, plan responsible familiarisation and distinguish online guidance from supervised physical practice.',
    sections: [
      { title: 'What this part of preparation involves', body: 'Individual obstacles are named in public SSB task overviews. The activity forms part of a wider selection process, not a standalone fitness certificate. The actual briefing provides the instructions that apply to your board. Avoid relying on online lists of supposedly universal obstacle sequences, time limits or marks unless they are part of the authoritative instructions given to you.' },
      { title: 'Familiarity is different from attempting apparatus', body: 'You can learn how to listen to instructions, organise personal preparation and ask sensible questions without trying an unfamiliar obstacle. Watching a video does not establish that equipment is safe or that a technique suits you. Practical familiarisation should take place with appropriate facilities and qualified supervision. Do not use rooftops, improvised ropes, furniture or unsupported structures as substitutes.' },
      { title: 'Plan around your actual starting point', body: 'If you have a health concern, injury or uncertainty about physical activity, seek individual advice from a qualified professional. This page does not prescribe a medical clearance or a training programme. For ordinary preparation, choose appropriate supervised activity and allow your instructor to account for your present ability. Avoid abrupt last-minute attempts to reproduce demanding tasks because an online account makes them sound essential.' },
      { title: 'Choose a provider carefully', body: 'Ask what facilities are available, who supervises practice and how equipment and participant safety are managed. Confirm whether the service is an explanation, general physical preparation or actual obstacle familiarisation. A one-to-one online session may help organise questions, but it is not physical task practice. Do not assume that a coaching advertisement implies the same setting or procedures as a selection board.' },
      { title: 'Review controllable preparation habits', body: 'Useful reflection includes whether you understood the instruction, asked about uncertainty and followed the agreed boundaries. Record practical difficulties for discussion with the relevant instructor rather than converting them into guesses about your selection result. The purpose is to improve preparation responsibly. Avoid comparing a single performance with a stranger’s online score or treating it as a diagnosis of officer suitability.' },
      { title: 'On the day', body: 'Follow the selection centre’s instructions and communicate a genuine health or safety concern to the responsible staff. Do not hide a problem to imitate an idea of confidence. Respect the task boundaries and other participants. The overall selection process also includes other forms of assessment; this guide makes no claim about how one obstacle attempt is interpreted or weighted.' },
    ], sources,
  },
];
