export const piArticles = [
  ['piq-preparation', 'How to Prepare Your PIQ for the SSB Personal Interview', 'Use your Personal Information Questionnaire as a truthful reflection aid, not a script.', 'Review each entry for accuracy, examples and questions it may naturally invite. Prepare to explain choices in your own words rather than memorising a biography.'],
  ['education-questions', 'SSB Personal Interview: Education Questions', 'Prepare for questions about your studies, subjects, results, choices and learning habits.', 'Know what you studied and why. Be ready to discuss a subject you enjoyed, a difficulty you faced and what you did next. Honest limits are more useful than invented expertise.'],
  ['family-background-questions', 'SSB Personal Interview: Family and Background Questions', 'Reflect on family, responsibilities, community and the experiences that shaped your preparation.', 'Respect privacy while preparing accurate context. Focus on your responsibilities and relationships; do not turn ordinary family life into a rehearsed achievement story.'],
  ['defence-motivation', 'SSB Personal Interview: Explaining Your Defence Motivation', 'Develop a considered account of why you want to serve and what you understand about the commitment.', 'Motivation can include service, challenge, leadership and professional interests. Connect it to what you have actually explored and acknowledge what you still need to learn.'],
  ['common-interview-mistakes', 'Common SSB Personal Interview Mistakes', 'Avoid avoidable preparation errors such as exaggeration, memorised answers and not listening to the question.', 'Practise answering the question asked, use specific experiences and pause when you need to think. A clear correction is better than defending an inaccurate claim.'],
  ['interview-preparation-for-repeaters', 'SSB Interview Preparation for Repeaters: What to Review', 'Turn your previous interview experience into a practical preparation plan based on observations and current responsibilities.', 'Separate what you remember happening from what you assume caused the result. Review your present preparation needs without reconstructing an assessor’s private judgment.'],
  ['current-affairs', 'Current Affairs for the SSB Personal Interview', 'Build an informed view of current affairs through reliable reading, context and reasoned discussion.', 'Follow a manageable number of issues and understand the people, institutions and choices involved. A headline collection is less useful than being able to explain why an issue matters.'],
  ['hobbies-and-interests', 'SSB Interview: Hobbies and Interests', 'Discuss interests through your actual participation, learning and curiosity.', 'Choose interests you really pursue. You do not need to replace an ordinary hobby with an impressive label: explain what you do, what you enjoy and what you have learned.'],
  ['personal-interview-questions', 'SSB Personal Interview Questions: Themes and Practice Prompts', 'Use questions about your experiences, choices and interests to practise thoughtful conversation.', 'These academy-created prompts help you reflect and practise explaining yourself. They are not a predicted question paper or an official interview script.'],
] as const;

type Section = { title: string; body: string; points?: string[] };
export const piSections: Record<string, Section[]> = {
  'piq-preparation': [
    { title: 'Start with accurate information', body: 'Use the Personal Information Questionnaire instructions supplied at your selection centre. For preparation, make a private factual record of education, dates, responsibilities, activities and achievements. Check uncertain details against your documents. Where information changes, understand the change rather than trying to preserve an old coaching version of your biography.' },
    { title: 'Understand the experiences behind the entries', body: 'For each substantial activity, recall your actual role, how often you participated, a difficulty and something you learned. Distinguish membership from leadership and participation from an award. If you wrote that you organised an event, be able to explain what you organised, who else helped and what decisions were yours. Ordinary, accurate details give a conversation substance.' },
    { title: 'Prepare for choices and changes', body: 'A change of subject, a gap, a lower result or a discontinued activity can be discussed clearly. Establish the sequence, your reasons at the time and what you did afterwards. Avoid composing an elaborate justification. If your judgment has changed, explain what you understand differently now.' },
    { title: 'A PIQ reflection exercise', body: 'Create three columns headed entry, example and question. Take five entries from your record, add a real example for each and write one natural follow-up question. Close the record and discuss two entries with a practice partner. Ask whether the explanation was understandable, not whether it sounded impressive.', points: ['Can I verify the facts?', 'Have I described my own contribution accurately?', 'What follow-up detail would help someone understand the experience?', 'Is there a current responsibility I should reflect on more carefully?'] },
    { title: 'Keep your preparation notes private', body: 'A practice partner rarely needs identity numbers, financial details or copies of sensitive documents. Share only what the exercise needs. For the actual process, provide the information requested through the official procedure. Use preparation notes to improve recall and reflection; do not memorise paragraphs for every entry.' },
  ],
  'education-questions': [
    { title: 'Know your educational journey', body: 'Review your subjects, results and important choices from school onward. Be ready to explain why you chose a stream or degree, what alternatives you considered and how your interests developed. If the choice was influenced by finances, family circumstances or available places, describe that context plainly.' },
    { title: 'Return to fundamentals', body: 'Choose core ideas from subjects you have studied and practise explaining them in simple language. For a technical project, describe the problem, method, your contribution and the limitations of the result. Revision should reconnect you with understanding, rather than produce an unrelated catalogue of impressive facts.' },
    { title: 'Discuss performance with perspective', body: 'For a disappointing result, separate circumstances from the habits you could control. Explain the revision or study changes you made and what happened afterwards. For a strong result, recognise others’ support and describe your own work. Neither an achievement nor a setback requires a dramatic personal narrative.' },
    { title: 'An education practice session', body: 'Select one subject and one project or assignment. Explain each to someone outside your course. Ask them to interrupt where a term is unclear, then answer a follow-up without returning to a prepared speech.', points: ['What problem or concept were you studying?', 'What did you personally do?', 'Which part did you find difficult?', 'What would you study or change next?'] },
    { title: 'When you cannot recall an answer', body: 'State the limit accurately. If you remember part of a concept, distinguish that from a guess. After practice, revisit the gap and explain the corrected idea aloud. Trying to defend a technical claim you do not understand makes an ordinary knowledge gap harder to resolve.' },
  ],
  'family-background-questions': [
    { title: 'Describe your setting in your own words', body: 'Reflect on the people, places and circumstances that shaped your everyday life. Your background need not be unusual to be worth discussing. Describe family members and relationships respectfully, and avoid adopting someone else’s account of what an ideal family should look like.' },
    { title: 'Focus on your responsibilities', body: 'Consider regular contributions at home: arranging a task, helping a sibling, managing a commitment or supporting someone while balancing studies. Explain what was expected, what you did and how you handled competing demands. A small responsibility performed reliably can provide a useful reflection example.' },
    { title: 'Understand your community', body: 'Learn about the place you come from through direct observation and reliable local information. What supports employment or education there? What challenge have you noticed? Distinguish what you personally observed from a broader claim that needs evidence. There is no need to invent social work or a community leadership role.' },
    { title: 'Practise a respectful conversation', body: 'Choose a family responsibility and a decision that required discussion with someone else. Explain the different needs involved, what you contributed and what the outcome taught you. Avoid casting another person as unreasonable merely to make your own role look stronger.', points: ['What was my responsibility?', 'What did another person need?', 'How did we agree on an action?', 'What do I now handle differently?'] },
    { title: 'Handle sensitive matters calmly', body: 'Some circumstances may be personal or difficult. Prepare a factual, respectful way to explain the relevant context without rehearsing emotional effects. In practice sessions, do not feel obliged to disclose sensitive information to unfamiliar people. Follow the actual interviewer’s question and seek clarification if you are unsure what detail is being requested.' },
  ],
  'defence-motivation': [
    { title: 'Connect motivation to what you have explored', body: 'Identify what first interested you, what you have learned since and why the commitment still appeals to you. Reading, a career talk, NCC experience or a conversation can inform your choice, but describe its actual influence. A patriotic slogan alone does not explain your personal decision.' },
    { title: 'Understand the route and role', body: 'Read the official information for your entry and service. Learn the broad training pathway and the responsibilities associated with the roles you are considering. Separate a confirmed feature from something you have only heard. If a preference depends on allocation or eligibility, recognise that uncertainty.' },
    { title: 'Think about the commitment', body: 'Reflect on discipline, learning, teamwork, demanding circumstances and being accountable for others. Consider how this career fits your interests and which aspects will require adjustment. Thoughtful motivation can include questions and realistic concerns; you do not need to claim that every challenge will be easy.' },
    { title: 'Build a motivation evidence note', body: 'Write down a reason for applying, the experience or research behind it and the next question you need to investigate. Discuss the note without reading it aloud. A practice partner should be able to understand why the choice matters to you.', points: ['What attracts me to service?', 'What have I done to understand the career?', 'Which responsibilities appeal to me?', 'What do I still need to learn?'] },
    { title: 'Discuss alternatives honestly', body: 'Having another educational or career plan does not require inventing a story of lifelong certainty. Explain the decisions you are making now and the work you are doing towards them. Avoid disparaging civilian careers or another service to make your preference sound stronger.' },
  ],
  'common-interview-mistakes': [
    { title: 'Answering the rehearsed question', body: 'A prepared speech can continue even after the interviewer asks something narrower. Practise listening for the actual question, giving a relevant answer and stopping when the point is clear. If several questions are asked together, keep their order in mind and ask for clarification when needed.' },
    { title: 'Inflating the example', body: 'Exaggeration often begins with a small change: describing a team result as your achievement or occasional participation as a sustained hobby. Review such language before practice. Explain the real contribution, including what others did and what you were unable to achieve.' },
    { title: 'Treating every correction as a threat', body: 'If you recognise an error, correct it briefly. If you disagree about an opinion, explain your reasoning courteously and remain willing to examine evidence. Spending the conversation defending every word can prevent you from listening or learning.' },
    { title: 'Replacing understanding with answer banks', body: 'A model answer may use experiences, vocabulary and assumptions that do not belong to you. Use question lists to identify topics for reflection, then close the list and talk about your own examples. Seek feedback on relevance and clarity rather than resemblance to a template.' },
    { title: 'Review one observable habit at a time', body: 'After a practice conversation, record the question, the difficulty and a small corrective action. For example, an unclear project explanation might call for revisiting the project and practising a simpler description. Avoid interpreting each pause or gesture as proof of an underlying selection verdict.', points: ['Did I answer the question asked?', 'Were my facts accurate?', 'Was my example understandable?', 'What one change will I practise next?'] },
  ],
  'interview-preparation-for-repeaters': [
    { title: 'Separate recollection from explanation', body: 'Write down what you remember: questions, your responses and moments when you could not explain an experience clearly. Keep that apart from assumptions such as “that answer caused my result.” A previous outcome does not disclose the interviewing officer’s reasoning or isolate the interview from the wider assessment.' },
    { title: 'Update the person you are describing', body: 'Review what has changed since the last attempt: education, employment, responsibilities, interests or choices. Reusing an old introduction can overlook your present circumstances. Consider what you have actually done with the time between attempts and which habits you are still developing.' },
    { title: 'Choose a specific preparation need', body: 'If you struggled to explain your degree project, revisit the work. If your current-affairs discussion lacked context, improve your reading method. If you often answered a different question, practise listening and concise responses. Match preparation to an observable difficulty instead of trying to construct a completely new personality.' },
    { title: 'Use a repeat-attempt review log', body: 'For two or three practice sessions, note the question theme, one observation and the follow-up action. Compare whether the same difficulty persists. Ask your partner to vary the questions and follow-ups so improvement means understanding rather than familiarity with a script.', points: ['What happened in practice?', 'What evidence supports my observation?', 'What action can I take?', 'What changed when I tried again?'] },
    { title: 'Discuss the previous attempt factually', body: 'Be accurate about the stage and result of previous attempts. Explain what you have worked on since without claiming to know an assessor’s private conclusion. A useful review can support a better preparation routine; it cannot promise a different board outcome.' },
  ],
  'current-affairs': [
    { title: 'Read for context', body: 'Choose a manageable set of national, international and local issues. For each, identify what happened, who is involved, why it matters and what remains uncertain. Start with reliable reporting and consult the relevant public institution for announcements or underlying documents. Check dates before treating an old development as current.' },
    { title: 'Separate facts and opinions', body: 'A policy announcement, a commentator’s forecast and your own judgment are different kinds of statements. Explain which you are using. Where reports disagree, identify the uncertainty rather than selecting the most dramatic claim. You need not have a fixed opinion on every developing issue.' },
    { title: 'Build a reasoned view', body: 'Consider the objective, the people affected, possible benefits and trade-offs. Explain what evidence supports your view and what information could change it. Courteous disagreement and an ability to revise a position are useful discussion habits; provocative certainty is not a preparation goal.' },
    { title: 'Try a short issue briefing', body: 'Choose an issue you have followed this week. Give a brief explanation to a partner, then invite questions about the background and alternatives. Return to your sources afterwards to check any factual gaps.', points: ['What is the development?', 'What background is needed?', 'Who may be affected?', 'What is my view, and why?', 'What remains uncertain?'] },
    { title: 'Keep preparation manageable', body: 'A regular reading and review habit is easier to sustain than accumulating a large list immediately before an interview. Revisit a few issues over time so you can recognise developments. Treat these topics as conversation preparation, not a guaranteed list of questions the board will ask.' },
  ],
  'hobbies-and-interests': [
    { title: 'Start with real participation', body: 'List what you actually do in your free time, how frequently and what attracts you to it. Reading, cooking, walking, music or repairing things can each provide worthwhile conversation. You do not need a rare hobby, and it is better to describe a developing interest accurately than claim expertise.' },
    { title: 'Know your own experience', body: 'Think about a recent book, activity, performance or project. What did you notice, enjoy or find difficult? If you play a sport, understand the basic rules and your own involvement. If you follow an activity more than you practise it, make that distinction clear.' },
    { title: 'Let curiosity guide learning', body: 'Explore a question that naturally follows from the hobby: a technique, an author’s other work or how a piece of equipment functions. This gives your interest depth through participation. Memorising trivia about a hobby you do not pursue is an inefficient substitute for doing and learning.' },
    { title: 'A hobby conversation exercise', body: 'Show or describe one recent example of your participation. Explain it to someone unfamiliar with the subject, then answer their questions. Notice where you rely on jargon and where an ordinary detail would make the explanation clearer.', points: ['What did I do recently?', 'Why do I enjoy this?', 'What have I learned?', 'What would I like to try next?'] },
    { title: 'When an interest has paused', body: 'Explain an interruption honestly, whether due to studies, work, access or changing interests. Consider whether you want to resume it and what that would involve. A truthful account of an occasional activity is more useful than describing a demanding routine that you do not maintain.' },
  ],
  'personal-interview-questions': [
    { title: 'Use themes, not predictions', body: 'The public selection process includes an interview, but an academy question list cannot establish what your interviewer will ask. These prompts are original preparation exercises. Use them to identify experiences you understand well and areas that need reflection, then practise answering follow-ups naturally.' },
    { title: 'Education and responsibility prompts', body: 'Choose questions that connect to your own circumstances. Explain the context, your action and what you learned without forcing every answer into an identical format.', points: ['Why did you choose your subject or course?', 'Which part of your studies challenged you?', 'What did you contribute to a recent project?', 'What responsibility do you handle regularly?', 'Describe a commitment that did not go to plan.'] },
    { title: 'Interests, people and choices', body: 'These themes work best when grounded in recent examples. Give enough context for a listener who does not know the people or activity involved. Respect other people’s privacy and describe your role fairly.', points: ['What have you enjoyed learning outside your course?', 'How do you spend time with friends?', 'What have you done recently in your main hobby?', 'How did you resolve a difference of opinion?', 'What advice changed a decision you made?'] },
    { title: 'Career and awareness prompts', body: 'Explore your reasons and understanding together. Where you lack information, identify the official source or reliable reference you will consult afterwards.', points: ['What have you learned about the entry you are applying for?', 'Which responsibilities attract you to the service?', 'What aspect of training do you expect to find demanding?', 'Which current issue have you followed, and why?', 'What are you doing now to prepare?'] },
    { title: 'Review the conversation', body: 'Have a partner select a few prompts in an unfamiliar order and ask natural follow-ups. Afterwards, review whether your answers were relevant, accurate and understandable. Identify one question that deserves more reflection. Repeating a polished answer word for word is not the objective of this exercise.' },
  ],
};
