import type { Metadata } from 'next';
import Link from 'next/link';
import { UserRound } from 'lucide-react';
import { withPageMetadata } from '@/lib/page-metadata';
import { Breadcrumbs, SiteFooter, SiteHeader } from '@/components/authority-shell';
const title = 'Commander Sharma Media Kit | March Ahead Academy';
const description = 'Approved biography themes and interview topics for colleges, NCC units, veteran organisations and defence-career publications.';
export const metadata: Metadata = withPageMetadata({ title, description, alternates: { canonical: '/media-kit/' }, openGraph: { title, description, url: '/media-kit/', type: 'website', images: ['/og-tri-service.webp'] } });
export default function Page() { return <main className="min-h-screen bg-white text-[#0a1e33]"><SiteHeader /><div className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><Breadcrumbs current="Media kit" tone="light" /><p className="section-kicker">For colleges, NCC units and publications</p><h1 className="mt-4 max-w-4xl font-heading text-4xl leading-tight sm:text-5xl">Commander Sharma Media Kit</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#536371]">A consistent reference for organisations inviting Commander Sharma to speak about defence careers, SSB preparation and responsible candidate development.</p><section className="mt-10 border-t-2 border-[#4b6228] pt-8"><div className="flex items-center gap-3"><UserRound className="text-[#4b6228]" size={28} aria-hidden="true" /><h2 className="font-heading text-3xl">Standard biography</h2></div><p className="mt-4 max-w-3xl leading-8 text-[#536371]">Commander Sulakshan Kumar Sharma (Retd.) is an Indian Navy veteran with 32 years of military service and 57 years of teaching experience. His background includes 4.5 years of independent Army and Navy recruitment experience, 3 years as an SSB psychologist, an MSc in Psychology, the DIPR Psychologist’s Course, a PG Diploma in Guidance and Counselling, teaching at the National Defence Academy and Naval College of Engineering, and service as Senior Service Psychologist at Naval Selection Centre, Bangalore. He leads March Ahead Academy’s personalised defence-career and SSB guidance.</p><p className="mt-4 text-sm leading-6 text-[#536371]">Use this wording consistently when describing his experience. Do not imply access to confidential selection methods or guarantee outcomes.</p></section><section className="mt-10 border-t border-[#d8e1dd] pt-8"><h2 className="font-heading text-3xl">Suggested talk and interview topics</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{['What an SSB psychologist assesses', 'Preparing for SSB psychology tests responsibly', 'NDA, CDS and AFCAT: choosing an officer-entry route', 'Why one-size-fits-all coaching fails', 'Preparation without scripts or false promises', 'Supporting students considering careers in the Armed Forces'].map((topic) => <li key={topic} className="border border-[#d8e1dd] p-4 text-[#536371]">{topic}</li>)}</ul></section><section className="mt-10 border-t border-[#d8e1dd] pt-8"><h2 className="font-heading text-3xl">Request a session or interview</h2><p className="mt-4 max-w-3xl leading-8 text-[#536371]">Colleges, NCC units, veteran organisations and publications can <Link className="text-link" href="/consultation/">request a consultation</Link>. The <Link className="text-link" href="/academy-evidence/">Academy evidence archive</Link> records completed public sessions when details and images are permitted.</p></section></div><SiteFooter /></main>; }
