import type { Metadata } from 'next';
import Link from 'next/link';
import { CalendarDays, MapPin, ArrowRight } from 'lucide-react';
import { withPageMetadata } from '@/lib/page-metadata';
import { Breadcrumbs, SiteFooter, SiteHeader } from '@/components/authority-shell';
const title = 'Academy Evidence: Talks and Guidance Sessions';
const description = 'A factual record of March Ahead Academy guidance sessions and public education work, with dates, context and permitted images.';
export const metadata: Metadata = withPageMetadata({ title: `${title} | March Ahead Academy`, description, alternates: { canonical: '/academy-evidence/' }, openGraph: { title, description, url: '/academy-evidence/', type: 'website', images: ['/og-tri-service.webp'] } });
export default function Page() { return <main className="min-h-screen bg-white text-[#0a1e33]"><SiteHeader /><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><Breadcrumbs current="Academy evidence" tone="light" /><p className="section-kicker">From the Academy · public record</p><h1 className="mt-4 max-w-4xl font-heading text-4xl leading-tight sm:text-5xl">{title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#536371]">Useful evidence of the academy’s work is recorded here with the detail we can responsibly confirm. This is a factual archive, not a selection-outcome claim.</p><article className="mt-10 border-t-2 border-[#4b6228] p-6"><div className="flex flex-wrap gap-4 text-sm font-semibold text-[#30471f]"><span className="inline-flex items-center gap-2"><CalendarDays size={18} aria-hidden="true" />26 July 2025</span><span className="inline-flex items-center gap-2"><MapPin size={18} aria-hidden="true" />Engineering college, Mumbai</span></div><h2 className="mt-5 font-heading text-3xl">Defence-career guidance session</h2><p className="mt-4 max-w-3xl leading-8 text-[#536371]">Commander Sharma led a guidance session for students considering careers in the Indian Armed Forces. The discussion connected entry information, preparation habits and the responsibilities of service.</p><img className="mt-6 w-full max-w-3xl" src="/events/mumbai-engineering-college-guidance-2025-07-26.webp" alt="Group photograph from a defence-career guidance session at an engineering college in Mumbai on 26 July 2025." /><p className="mt-5 leading-8 text-[#536371]">For invitations or a future session, <Link className="text-link" href="/consultation/">book a consultation</Link>. For the mentor’s background, <Link className="text-link" href="/authors/cdr-sulakshan-kumar-sharma/">read Commander Sharma’s profile</Link>.</p></article><section className="mt-12 border-t border-[#d8e1dd] pt-8"><h2 className="font-heading text-3xl">How evidence is added</h2><p className="mt-4 max-w-3xl leading-8 text-[#536371]">We add a date, setting, topic and permitted image only when those details can be confirmed. Future talks and appearances will be labelled as upcoming until they take place.</p></section></div><SiteFooter /></main>; }
