import type { Metadata } from 'next';
import { AuthorityPage } from '@/components/authority-shell';
export const metadata: Metadata = { alternates: { canonical: '/eligibility' }, title: 'Defence Eligibility and Medical Standards | March Ahead Academy', description: 'Learn how age, education, medical and physical requirements should be verified.' };
export default function Page() { return <AuthorityPage eyebrow="Eligibility" title="Eligibility is a chain, not a checkbox" lede="A candidate must satisfy every applicable condition for the exact service, entry and intake. Missing information should produce “unable to determine,” not false confidence." sections={[
  { title: 'Identity and status conditions', body: 'Nationality, sex, marital status and exact date-of-birth windows must be checked against the controlling notification. Approximate age calculators can mislead at boundaries.' },
  { title: 'Educational conditions', body: 'Qualification name alone is not enough. Verify subjects studied, marks, recognised institution or degree, final-year rules and documentary deadlines.', points: ['Check Class 12 subject requirements separately from degree requirements.', 'Do not assume equivalent qualifications are accepted unless the notice says so.', 'Do not transfer one branch requirement to another.'] },
  { title: 'Medical and physical standards', body: 'Officer medical standards, Army recruiting physical tests, Navy Agniveer tests and Agniveervayu requirements are not interchangeable. Branch and aircrew standards may differ, and only authorised service medical boards decide fitness.' },
  { title: 'How our future checker will respond', body: 'The tool will show the candidate inputs, reasoning, source clause and limits. It will return likely eligible, likely not eligible, or unable to determine—and will never replace official verification.' },
]} sources={[{label:'UPSC active examinations',href:'https://www.upsc.gov.in/examinations/active-exams'},{label:'Join Indian Army',href:'https://www.joinindianarmy.nic.in/'},{label:'Join Indian Navy',href:'https://www.joinindiannavy.gov.in/'},{label:'Indian Air Force careers',href:'https://www.careerairforce.gov.in/'}]} related={[{label:'Career Path Finder',href:'/career-paths'},{label:'Notifications tracker',href:'/notifications'},{label:'SSB guide',href:'/selection/ssb'}]} />; }
